import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
          <meta charset="utf-8" />

          <meta http-equiv="X-UA-Compatible" content="IE=edge" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />

          <meta name="description" content="" />
          <meta name="author" content="" />

          <title>Home</title>
          {/* <!-- Standard Favicon --> */}
          <link rel="icon" href="img/fav/favicon-96x96.png" />

          {/* <!-- Touch Icons - iOS and Android 2.1+ --> */}
          <link rel="apple-touch-icon" href="img/fav/android-icon-48x48.png" />
          <link
            rel="apple-touch-icon"
            sizes="72x72"
            href="img/fav/android-icon-72x72.png"
          />
          <link
            rel="apple-touch-icon"
            sizes="114x114"
            href="img/fav/apple-icon-114x114.png"
          />

          {/* <!--bootstrap v5.2.3 --> */}
          <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" />
          {/* <!--flag css--> */}
          <link rel="stylesheet" type="text/css" href="css/flags.css" />
          {/* <!--meanmenu--> */}
          <link rel="stylesheet" type="text/css" href="css/meanmenu.css" />
          {/* <!--icons--> */}
          <link rel="stylesheet" type="text/css" href="css/boxicons.min.css" />
          {/* <!--aos--> */}
          <link rel="stylesheet" type="text/css" href="css/aos.css" />
          {/* <!--slick slider--> */}
          <link rel="stylesheet" type="text/css" href="css/slick.css" />
          {/* <!--main style--> */}
          <link rel="stylesheet" type="text/css" href="css/style.css" />

          {/* <!--modernizr--> */}
          <script src="js/vendor/modernizr.js"></script>

          {/* <!--[if lt IE 9]> */}
          <script src="js/html5/respond.min.js"></script>
          {/* <![endif]--> */}
        </head>

        <body data-spy="scroll" data-target=".navbar" data-offset="60">
          {children}
          {/* <!-- Return to Top --> */}
          <a href="javascript:" id="return-to-top">
            <i class="bx bx-chevron-up"></i>
          </a>

          {/* <!--jquery--> */}
          <script src="js/jquery.js"></script>
          {/* <!--bootstrap bundle v5.2.3--> */}
          <script src="js/vendor/bootstrap.bundle.js"></script>
          {/* <!--meanmenu--> */}
          <script src="js/vendor/jquery.meanmenu.js"></script>
          {/* <!--flag--> */}
          <script src="js/vendor/jquery.flagstrap.min.js"></script>
          {/* <!--aos--> */}
          <script src="js/vendor/aos.js"></script>
          {/* <!--slick--> */}
          <script src="js/vendor/slick.min.js"></script>
          {/* <!--easing js--> */}
          <script src="js/vendor/easing.js"></script>
          {/* <!--main script--> */}
          <script src="js/main.js"></script>
        </body>
      </html>
    </>
  );
}
